name: "Test"
on: [push, pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        env:
            TEST: "lint"
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 14

            - uses: actions/checkout@v2

            - run: npm ci

            - run: bash ./scripts/ci.sh
    unit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [11, 12, 13, 14]
        env:
            TEST: "unit"
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - uses: actions/checkout@v2

            - run: npm ci

            - run: bash ./scripts/ci.sh
    e2e:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                testCmd:
                    [
                        'unit_and_e2e_clients',
# Disabled until https://github.com/oasisprotocol/web3-tests/issues/2 is fixed.
#                        'e2e_browsers',
#                        'e2e_ganache',
#                        'e2e_mosaic',
                        'e2e_gnosis_dex',
                    ]
        env:
            TEST: ${{ matrix.testCmd }}
            INFURA_HTTP: ${{ secrets.INFURA_HTTP }}
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - uses: actions/checkout@v2

            - run: npm ci

            - run: bash ./scripts/ci.sh

