name: "Test"
on: [push, pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        env:
            TEST: "lint"
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 14

            - uses: actions/checkout@v2

            - run: npm ci

            - run: bash ./scripts/ci.sh
#    unit:
#        runs-on: ubuntu-latest
#        strategy:
#            matrix:
#                node: [11, 12, 13, 14]
#        env:
#            TEST: "unit"
#        steps:
#            - uses: actions/setup-node@v1
#              with:
#                  node-version: ${{ matrix.node }}
#
#            - uses: actions/checkout@v2
#
#            - run: npm ci
#
#            - run: bash ./scripts/ci.sh
    build-web3:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: 'oasisprotocol/oasis-evm-web3-gateway'
                  ref: 'main'

            - uses: actions/setup-go@v2
              with:
                  go-version: '^1.17'

            - run: go build

            - uses: actions/upload-artifact@v2
              with:
                  name: oasis-evm-web3-gateway
                  path: |
                      oasis-evm-web3-gateway
                      conf/tests.yml

            - uses: actions/upload-artifact@v2
              with:
                  name: oasis-evm-web3-gateway-tools
                  path: |
                      tests/tools/spinup-oasis-stack.sh
                      tests/tools/staking_genesis.json

    build-oasis-deposit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-go@v2
              with:
                  go-version: '^1.17'

            - run: |
                cd test/tools/oasis-deposit
                go build

            - uses: actions/upload-artifact@v2
              with:
                  name: oasis-deposit
                  path: test/tools/oasis-deposit/oasis-deposit
    e2e-oasis:
        runs-on: ubuntu-latest
        needs:
            - build-web3
            - build-oasis-deposit
        strategy:
            fail-fast: false
            matrix:
                testCmd:
                    [
                        'e2e_oasis'
                    ]
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_HOST: 127.0.0.1
                    POSTGRES_PORT: 5432
                    POSTGRES_DB: postgres
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432:5432
        env:
            OASIS_CORE_VERSION: 21.3.6
            OASIS_NODE: ${{ github.workspace }}/oasis_core/oasis-node
            OASIS_NET_RUNNER: ${{ github.workspace }}/oasis_core/oasis-net-runner
            OASIS_EMERALD_VERSION: 6.0.0
            GATEWAY__CHAIN_ID: 42261
            OASIS_EMERALD_PARATIME: ${{ github.workspace }}/oasis_core/emerald-paratime
            OASIS_NODE_DATADIR: /tmp/eth-runtime-test
            OASIS_EVM_WEB3_GATEWAY: ${{ github.workspace }}/scripts/oasis-evm-web3-gateway
            TEST: ${{ matrix.testCmd }}
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.17.0
            - uses: actions/checkout@v2

            - run: npm ci

            - name: Install prerequisites
              run: |
                  sudo apt update && sudo apt install bubblewrap -y
                  wget "https://github.com/oasisprotocol/oasis-core/releases/download/v${OASIS_CORE_VERSION}/oasis_core_${OASIS_CORE_VERSION}_linux_amd64.tar.gz"
                  tar xfvz "oasis_core_${OASIS_CORE_VERSION}_linux_amd64.tar.gz"
                  mkdir -p "$(dirname ${OASIS_NODE})"
                  mv "oasis_core_${OASIS_CORE_VERSION}_linux_amd64/oasis-node" "${OASIS_NODE}"
                  mkdir -p "$(dirname ${OASIS_NET_RUNNER})"
                  mv "oasis_core_${OASIS_CORE_VERSION}_linux_amd64/oasis-net-runner" "${OASIS_NET_RUNNER}"
                  mkdir -p "$(dirname ${OASIS_EMERALD_PARATIME})"
                  wget "https://github.com/oasisprotocol/emerald-paratime/releases/download/v${OASIS_EMERALD_VERSION}/emerald-paratime" -O "${OASIS_EMERALD_PARATIME}"
                  chmod a+x "${OASIS_EMERALD_PARATIME}"

            - uses: actions/download-artifact@v2
              with:
                name: oasis-evm-web3-gateway
                path: scripts
            - run: chmod a+x ${OASIS_EVM_WEB3_GATEWAY}

            - uses: actions/download-artifact@v2
              with:
                  name: oasis-evm-web3-gateway-tools
                  path: scripts
            - run: chmod a+x scripts/spinup-oasis-stack.sh

            - uses: actions/download-artifact@v2
              with:
                name: oasis-deposit
                path: test/tools/oasis-deposit
            - run: chmod a+x test/tools/oasis-deposit/oasis-deposit

            - name: Spinup oasis-node
              run: |
                  scripts/spinup-oasis-stack.sh > /dev/null &
                  sleep 10

            - run: ${OASIS_EVM_WEB3_GATEWAY} --config scripts/conf/tests.yml &

            - run: bash ./scripts/e2e.oasis.sh

